package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"graphql_crud_api/db"
	"graphql_crud_api/graph/model"
	"graphql_crud_api/models"
	"log"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, email string) (*model.User, error) {
	collection := db.Client.Database("graphql").Collection("users")

	user := models.User{
		Name:  name,
		Email: email,
	}

	res, err := collection.InsertOne(ctx, user)
	if err != nil {
		log.Println("Insert Error:", err) // 👈 ADD THIS
		return nil, err
	}

	objID := res.InsertedID

	idHex := ""

	switch v := objID.(type) {
	case bson.ObjectID:
		idHex = v.Hex()
	default:
		idHex = fmt.Sprintf("%v", v)
	}

	return &model.User{
		ID:    idHex,
		Name:  name,
		Email: email,
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, name string, email string) (*model.User, error) {

	collection := db.Client.Database("graphql").Collection("users")

	objID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid ID")
	}

	filter := bson.M{"_id": objID}
	update := bson.M{
		"$set": bson.M{
			"name":  name,
			"email": email,
		},
	}

	_, err = collection.UpdateOne(ctx, filter, update)
	if err != nil {
		log.Println("Update error", err)
		return nil, err
	}

	return &model.User{
		ID:    id,
		Name:  name,
		Email: email,
	}, nil

}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (string, error) {

	collection := db.Client.Database("graphql").Collection("users")

	objID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return "", fmt.Errorf("invalid ID")
	}

	filter := bson.M{"_id": objID}

	_, err = collection.DeleteOne(ctx, filter)
	if err != nil {
		log.Println("Delete error", err)
		return "", err
	}

	return "User deleted successfully", nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	collection := db.Client.Database("graphql").Collection("users")

	cursor, err := collection.Find(ctx, bson.M{})
	if err != nil {
		log.Println("Find Error:", err)
		return nil, err
	}
	defer cursor.Close(ctx)

	var users []*model.User

	for cursor.Next(ctx) {
		var user models.User

		if err := cursor.Decode(&user); err != nil {
			log.Println("Decode Error:", err)
			continue
		}

		users = append(users, &model.User{
			ID:    user.ID.Hex(),
			Name:  user.Name,
			Email: user.Email,
		})
	}

	return users, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
